### ISSUE TITLE
Multi line json data

### ISSUE THREAD

**Issue by gjuoun** [joelwmale/webhook-action#11]
Hey, thanks for creating this webhook!
But I found issues when I want to send multi-line literals json data: 
like this
```yaml
      - name: Webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ""
          data: >
            {"authorization": "mysecret", 
            "domain": "...", 
            "docker-image": "..." }
```

Do you know how to make it work?
