### ISSUE TITLE
Request failed with status code undefined

### ISSUE THREAD

**Issue by arnaudoff** [joelwmale/webhook-action#385]
Hi, I'm getting the following error:

Run joelwmale/webhook-action@fd99bb3b8272237103e349e9bb4d9b0ead9a217c
Sending webhook request to ***
Error: Received status code: undefined
(node:2044) UnhandledPromiseRejectionWarning: Error: Request failed with status code: undefined
    at error (/home/runner/work/_actions/joelwmale/webhook-action/fd99bb3b8272237103e349e9bb4d9b0ead9a217c/dist/main.js:92:11)
    at /home/runner/work/_actions/joelwmale/webhook-action/fd99bb3b8272237103e349e9bb4d9b0ead9a217c/dist/main.js:83:17
    at processTicksAndRejections (internal/process/task_queues.js:93:

This is my config:
```
  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-18.04
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@fd99bb3b8272237103e349e9bb4d9b0ead9a217c
        with:
          url: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          headers: "{ 'X-Hook-Auth-Password': '${{ secrets.DEPLOY_WEBHOOK_SECRET }}'}"
```
 
The url is in the form `http://<ip>:<port>/hooks/<name of hook>`. I tried without `http://` prefix, still doesnt work. What's wrong and is there an easy way to debug it? I don't understand anything from this message. Did the request fail, or it passed but HTTP error code was returned? Is there something wrong in the setup?

Thanks in advance.
