### ISSUE TITLE
Action should not be using a deprecated `set-output` method

### ISSUE THREAD

**Issue by jkulak** [joelwmale/webhook-action#593]
Wen running the newest version of the action, there is a Warning stating the action is using a  the deprecated `set-output` method.

```
Sending webhook request to ***/deploy-api
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using
Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Received status code: 200
```

My config
```
    deploy-api:
        name: Redeploy API
        runs-on: ubuntu-latest
        needs: [build-and-push]
        steps:
            - name: Deploy docker container webhook
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
            - name: Webhook call
              uses: joelwmale/webhook-action@master
              with:
                  url: ${{ secrets.DEPLOY_WEBHOOK_URL }}/deploy-api
                  headers: '{"secret": "${{ secrets.WEBHOOK_SECRET }}"}'
```

Source: [https://github.com/jkulak/smartplaylist-backend/actions/runs/3347471589/jobs/5545500696#step:3:7](https://github.com/jkulak/smartplaylist-backend/actions/runs/3347471589/jobs/5545500696#step:3:7)

**Comment by natlibfi-jonollil** [comment]
``` yaml
openshift-webhook:
    name: OpenShift webhook for image builder
    needs: [build-node-versions, njsscan]
    runs-on: ubuntu-latest

    steps:
      - uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"event": "${{ github.event_name }}","uri": "${{ github.repository }}","ref": "${{ github.ref }}","commit": "${{ github.sha }}"}'
```

Bit simpler webhook trigger for OpenShift image build
