### ISSUE TITLE
Doc errors

### ISSUE THREAD

**Issue by jasongitmail** [joelwmale/webhook-action#6]
The examples use this format:

```
- name: Webhook
  uses: joelwmale/webhook-action@master
  env:
    WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
  with:
    data: "Hello from github actions!"
```
but this fails:

<img width="458" alt="err" src="https://user-images.githubusercontent.com/50032291/66974002-37458700-f089-11e9-90f1-40a7e588d588.png">

However, this format succeeds:

```
- name: Webhook
  uses: joelwmale/webhook-action@master
  env:
    WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    data: "Hello from github actions!"
```

The suggested format for using a hash would be better as something like `uses: joelwmale/webhook-action@6b83612` because `uses: joelwmale/webhook-action@master@6b83612` will fail. 

This was a good start though. I appreciate it. I think a [Github Javascript action](https://github.com/actions/javascript-action) might have a shorter build time (to conserve build minutes), so it may be something to experiment with. I'll try when I have time.
