### ISSUE TITLE
Webhook sent twice on the newest version

### ISSUE THREAD

**Issue by omer2500** [joelwmale/webhook-action#676]
Hi,

We have a job that sends a webhook on a workflow
A couple of hours ago it started to send the webhook twice each time it ran.

we are using the tag master and I saw that a new version was released 3 days ago 

what I see is that we have another step called Post webhook that sends the webhook again and have the same logs

on 2.3.2 it doesn't happen 

I'm attaching pictures to show the issue

latest version:
![image](https://github.com/joelwmale/webhook-action/assets/29802207/4445e338-563d-4cdf-a418-2a507416fd04)

2.3.2:

![image](https://github.com/joelwmale/webhook-action/assets/29802207/7bd953db-cc53-41e4-8c8a-0e44d1be34ed)

is this intentional? am I missing some new configuration ? or is this a bug?

Thanks!

**Comment by joelwmale** [comment]
@omer2500 Can you send me the workflow file and how you've set up this step?

Testing this on the master version (prior to release, using `develop`) never sent the webhook twice.

**Comment by omer2500** [comment]
Hi, @joelwmale
I have no step called Post webhook,
the log is the same except It mentions its a cleanup job but right after that log I see the log that indicated webhook sent 

just to mention I'm running on self-hosted runners on aws ,
so you might need to adjust the runs-on property

just play with the tag of the version from master to 2.3.2
and check the steps that were executed 

this is the workflow I used to test:
```
name: test
on:
    pull_request:
        branches:
            - master
jobs:
    send_bq_data:
        runs-on: self-hosted
        steps:
          - name: Webhook
            uses: joelwmale/webhook-action@master
            with:
              url: https://example.com/webhook
              headers: '{"Content-Type": "application/json"}'
              body: '{"message": "Hello, World!"}'
```
