### ISSUE TITLE
Support for custom headers

### ISSUE THREAD

**Issue by prescottprue** [joelwmale/webhook-action#8]
Thanks for the package! It would be awesome if passing headers was supported. Maybe something like so:

```yaml
- name: Webhook
   uses: joelwmale/webhook-action@master
   env:
     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
     data: "{'deployment': 'finished', 'project': 'actions'}"
     headers: ['Some-Header: 123ASDF', 'Some-Other-Header: 123ASDF']
```

I have also seen `with` commonly used for actions since `env`:

```yaml
- name: Webhook
   uses: joelwmale/webhook-action@master
   with:
     headers: ['Some-Header: 123ASDF']
   env:
     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
     data: "{'deployment': 'finished', 'project': 'actions'}"
```
